apiVersion: v1
kind: Service
metadata:
  name: {{ include "mfe.app1.fullname" . }}
  labels:
    app: mfe
    container: app1
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.services.app1.type }}
  ports:
    - port: {{ .Values.services.app1.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mfe
    container: app1
    release: {{ .Release.Name }}
