apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mfe.app1.fullname" . }}-nginx-config
  labels:
    app: mfe
    release: {{ .Release.Name }}
data:
  config: |
{{ include "mfe.nginx-config" .Values.nginx.app1 | indent 4 }}