apiVersion: v1
kind: Service
metadata:
  name: {{ include "mfe.container.fullname" . }}
  labels:
    app: mfe
    container: container
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.services.container.type }}
  ports:
    - port: {{ .Values.services.container.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mfe
    container: container
    release: {{ .Release.Name }}
