# Default values for mfe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  container:
    repository: mfe/container
    pullPolicy: IfNotPresent
    tag: latest
  app1:
    repository: mfe/app1
    pullPolicy: IfNotPresent
    tag: latest

services:
  container:
    type: ClusterIP
    port: 80
  app1:
    type: ClusterIP
    port: 80

nginx:
  container:
    rewrites: []
  app1: {}
